name: Testing Actions

on:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      # You can test your matrix by printing the current Python version
      - name: Run tests
        run: python sample_unit_tests.py